services:
  # Fullstack Web Service (Frontend + Backend in 1 Single Deployment)
  - type: web
    name: electricity-unit-calculator
    env: python
    region: singapore
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./wattwise.db
